// <auto-generated />
namespace HoosierVolunteer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zipcity1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zipcity1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809171907100_zipcity1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
